### ISSUE TITLE
muta_cluster never complete

### ISSUE THREAD

**Issue by yuhanH** [veltenlab/mitoClone#1]
Hi, 
I am trying to use mitoClone to get the clone information from single cell RNA data. 
Before the step `muta_cluster`, all steps work well. But when i ran `muta_cluster`, it never finishes... I only used 300 cells. 
I also tried to decrease `time`, but still could not get results from `muta_cluster`. 
Any suggestions would be very helpful!

**Comment by benstory** [comment]
Hi yuhan,
Thanks for the post.

1. Did you have any success running the example in the vignette?
2. Were you able to successfully install and acquire a license to run Gurobi?
3. Do you get any kind of error message?

**Comment by yuhanH** [comment]
Hi, 
I can successfully run the example. I find out that the issue should be related to `mutationCallsFromCohort`
After I ran `mutationCallsFromCohort` on my samples, I got around 4K mutations.  Most of mutations end with two `..` such as  `X2943G..`
Do you have ideas about what steps i may make a mistake? 
Thanks!

**Comment by velten-lab** [comment]
Hi Yuhan, 4k seems very high. 
Generally would recommend to choose some mutations that you trust (for example, mutations identified/validated by exome sequencing) and then use the association tests described in the "Variant calling and blacklist creation (using cohort data)" vignette to filter your set of 4k further. This strategy might further help to set better filters for the mutationCallsFromCohort function. Try to get your list down to the 20-50 mutations that you trust most based on associations, % of cells affected, coverage, etc.
In your case the problem might be related to variant calling, since the mutations end with `..`. What's your input to mutationCallsFromCohort?

**Comment by yuhanH** [comment]
My input is a list of bam files. I find that only one sample has this `..` issue.

**Comment by hrstu** [comment]
Hi, I have had the same issue where one sample has over a thousand variants called, most ending in `..` . I have three samples and only one of them has this issue. The other two call around 8-10 variants. I am also unable to use muta_cluster from the output of mutationCallsFromCohort, but rather I get an 'invalid row.names' error instead of the command never completing. I ran baseCountsFromBamList to get my CountTable.

**Comment by benstory** [comment]
The source of the '..' mutations is due to gaps (or splicing) in the alignments. The character parsing within R ultimately converts a '-' into a '.'. 

The question as to whether we want to include these types of phenomena in our set of valid "mutations" is uncertain. 

Realistically it seems to be more of a quality control issue with the alignments, biologically you should see minimal to no spliced reads across mitochondrial genes.

In the meantime I added the ability to ignore insertions, deletions, and gaps in the `baseCountsFromBamList` function through an extra parameter `ignore_nonstandard` setting this to `TRUE` will allow you to **ignore** the spliced alignments and should result in a lack of `..` calls. I left the N nucleotide calls in the pileup step because otherwise you might accidentally call variants in very low quality regions.

**Comment by yuhanH** [comment]
Thanks!
